<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheOne.Application\TheOne.Application.csproj" />
    <ProjectReference Include="..\TheOne.Domain\TheOne.Domain.csproj" />
  </ItemGroup>

</Project>
